#!/usr/bin/env bash
# configures a server to listening on port 80 of all servers active IPv4 IPs

# creates a symbolic link (-s option) between the Nginx configuration file
# and the enabled sites directory
ln -sf /etc/nginx/sites-available/default /etc/nginx/sites-enabled/default
# restart nginx
service nginx start
# terminate first nginx process ID
kill "$(pgrep 'nginx' | head -1)"
